name: C Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc clang-format make

      # Step 3: Build the project
      - name: Build Project
        run: make

      # Step 4: Check code formatting (fail if wrong)
      - name: Check Code Formatting
        run: |
          # Run clang-format in check mode
          unformatted=$(clang-format --dry-run --Werror src/*.c src/include/*.h 2>&1) || true
          if [ -n "$unformatted" ]; then
            echo "Code is not properly formatted:"
            echo "$unformatted"
            exit 1
          fi

      # Step 5: Optional - Clean build artifacts
      - name: Clean Build
        run: make clean
